apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnb-exporter
  template:
    metadata:
      labels:
        app: cnb-exporter
    spec:
      containers:
        - name: cnb-exporter
          image: krab55/cnb-prometheus-exporter:dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cnb-exporter-service
spec:
  selector:
    app: cnb-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 8080
  type: ClusterIP
