apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnb-exporter
  template:
    metadata:
      labels:
        app: cnb-exporter
    spec:
      containers:
        - name: cnb-exporter
          image: krab55/cnb-prometheus-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cnb-exporter-service
spec:
  selector:
    app: cnb-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 8080
  type: ClusterIP
