apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-alarm-config
data:
  SLACK_BOT_TOKEN: "xoxb-"
  SLACK_SIGNING_SECRET: ""
  SLACK_APP_TOKEN: "xapp-1-" 
  MQTT_SERVER: "mqtt://server:port"
  MQTT_TOPIC: "zigbee2mqtt/0xXXXXXX"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: slack-alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-alarm
  template:
    metadata:
      labels:
        app: slack-alarm
    spec:
      containers:
        - name: slack-alarm
          image: registry/slack-alarm:latest
          envFrom:
            - configMapRef:
                name: slack-alarm-config