apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app
  namespace: app # Change to your desired namespace
spec:
  refreshInterval: 1h # Adjust refresh interval as needed
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: app # Name of the Kubernetes secret to create
    creationPolicy: Owner
  data:
    # DATABASE_URL
    - secretKey: DATABASE_URL  # Key in the resulting Kubernetes Secret
      remoteRef:
        key: app/mysql  # Path in Vault
        property: DATABASE_URL       # Specific property within the Vault secret

    # SHADOW_DATABASE_URL
    - secretKey: SHADOW_DATABASE_URL  # Key in the resulting Kubernetes Secret
      remoteRef:
        key: app/mysql  # Path in Vault
        property: SHADOW_DATABASE_URL  # Specific property within the Vault secret
