set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=/etc/vim/bundle/Vundle.vim
set rtp+=/etc/vim/bundle/vim-airline
set rtp+=/etc/vim/bundle/vim-airline-themes
set rtp+=/etc/vim
set backspace=2
execute pathogen#infect()
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Dependencies
Plugin 'prabirshrestha/async.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

colo darkblue
syntax on
highlight Comment ctermfg=green
set laststatus=2
let &t_Co=256
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

" Intend
 map <Tab> >
 map <S-Tab> <
