name: plantuml

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - 'Kubernetes/plantuml/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Kubernetes/plantuml/**'

jobs:
  build-docker-image:
    runs-on: self-hosted-linux

    env:
        IMAGE_NAME: plantuml

    steps:    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push to both registries
        uses: docker/build-push-action@v6
        with:
          context: ./Kubernetes/${{ env.IMAGE_NAME }}
          file: ./Kubernetes/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        