name: Selenium CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Docker/selenium-firefox/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Docker/selenium-firefox/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: cd Docker/selenium-firefox && docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/selenium-firefox:$(date +%s) --tag ${{ secrets.DOCKERHUB_USERNAME }}/selenium-firefox:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/selenium-firefox --all-tags
